spring.application.name=SpringSecEx

# spring.security.user.name=root
# spring.security.user.password=root

spring.datasource.url=jdbc:postgresql://localhost:5432/spring_sec_db
spring.datasource.username=postgres
spring.datasource.password=postgre
spring.jpa.hibernate.ddl-auto=update
